tango_with_django_project/rango/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views


app_name = 'rango'
urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^category/(?P<category_name_slug>[\w-]+)/$',
        views.show_category, name='show_category'),
    url(r'^page/(?P<page_name_slug>[\w-]+)/$',
        views.show_page, name='show_page'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w-]+)/add_page/$',
        views.add_page, name='add_page'),
    #url(r'^register/$', views.register, name='register'),
    #url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    #url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^search/$',views.search, name='search'),
    url(r'^register_profile/$', views.register, name='register'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^like/$', views.like_category, name='like_category'),




]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from rango import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.shortcuts import render



class MyRegistrationView(RegistrationView):
 	def get_success_url(self, user):
 		return '/rango/register_profile'


def PasswordChangeDone(request):
	return views.index(request)

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^accounts/register/$', MyRegistrationView.as_view(),name='registration_register'),
	url(r'^accounts/password/change/done/$', PasswordChangeDone,name='password_change_done'),
	url(r'^accounts/', include('registration.backends.simple.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True,unique=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


    class Meta:
	    verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128 )
    url = models.URLField()
    views = models.IntegerField(default=0)
    txt = models.TextField(blank=True)
    file = models.FileField(upload_to='upload_file_from_page', max_length=100, blank=True)
    slug = models.SlugField(blank=True)


    def save(self, *args, **kwargs):
         self.slug = slugify(self.title)
         super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class UserProfile(models.Model):

    user= models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:

        #connect with model-category
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):

    title = forms.CharField(max_length=128,
                            help_text='Please enter the title of the page.')
    url = forms.URLField(max_length=128,
                         help_text='Please enter the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    txt = forms.CharField(widget=forms.Textarea, help_text='Please enter the description of the page or the attachment you may upload.')

    file = forms.FileField(max_length=100, help_text='Please upload your attachment of the page.', required=False)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # def clean(self):
    #     cleaned_data = self.cleaned_data
    #     url = cleaned_data.get('url')
    #
    #     if url and not url.startwitch('http://'):
    #         url = 'http://'+url
    #         cleaned_data['url'] = url
    #
    #         return cleaned_data

    class Meta:
        model = Page
        exclude = ('category',)

class UserForm(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from datetime import datetime
from django.conf import settings
from rango.webhose_search import run_query


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val



def visitor_cookie_handler(request):

    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request,'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds >0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits



def index(request):
    #request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    print(page_list)
    visitor_cookie_handler(request)
    context_dict = {'categories': category_list, 'pages': page_list}
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/index.html', context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        category.views += 1
        category.save()
        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages

        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None


    return render(request, 'rango/category.html', context_dict)

def show_page(request, page_name_slug):
    context_dict = {}

    try:
        pages = Page.objects.get(slug=page_name_slug)
        pages.views += 1
        pages.save()
        context_dict['pages'] = pages

    except Page.DoesNotExist:
        context_dict['pages'] = None


    return render(request, 'rango/page.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()


    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)

            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html',{'form':form})



@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                if 'file' in request.FILES:
                    page.file = request.FILES['file']
                page.save()
                return show_category(request, category_name_slug)
            else:
                print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)








def about(request):
    # if request.session.test_cookie_worked():
    #     print("TEST COOKIE WORKED")
    #     request.session.delete_test_cookie()
    #context_dict = {'boldmessage': "love, loop, forever!!!"}
    return render(request, 'rango/about.html')

@login_required
def register(request):
    registered = False
    profile_form = UserProfileForm()
    if request.method == 'POST':
        profile_form = UserProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():

            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()

            registered = True

        else:
                print(profile_form.errors)


    return render(request,
                  'rango/profile_registration.html',
                  {'registered':registered,
                   'profile_form': profile_form,
                   'registered':registered})


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

# @login_required
# def user_logout(request):
#
#     logout(request)
#
#     return HttpResponseRedirect(reverse('index'))

def search(request):
    result_list = []
    query =''
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:

            result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list':result_list, 'query':query})


def profile(request,username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExits:
        return redirect('index')

    userform = UserForm({'username':user.username, 'email':user.email})
    #print(userform.username)
    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    userprofileform = UserProfileForm({'website':userprofile.website, 'picture':userprofile.picture})

    if request.method =='POST':
        userform = UserForm(request.POST, instance = user)
        userprofileform = UserProfileForm(request.POST, request.FILES, instance=user)
        if userprofileform.is_valid() and userform.is_valid():
            userform.save(commit=True)
            userprofileform.save(commit=True)
            return redirect('index')
        else:
            if not userprofileform.is_valid():
                print(userprofileforms.error)
            else:
                print(userform.error)

    return render(request, 'rango/profile.html', {'userprofile': userprofile, 'selecteduser': user, 'userform': userform, 'userprofileform': userprofileform})


@login_required
def like_category(request):

    cat_id = None
    print(9999)
    likes = 10
    if request.method == 'GET':

        cat_id = request.GET['category_id']

        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes +1
                cat.likes = likes
                cat.save()

    return HttpResponse(likes)

#def suggest_category():

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}



{% block title_block %}
    关于我们
{% endblock %}

{% block body_block %}
<p >这里是屁屁鸡和二狗一起搭建的第一个网站——何屁鸡的小窝。小窝里记录着屁屁鸡和二狗学习搭建网站的每一步和一些学习资料分享。
    希望屁屁鸡和二狗可以借助屁屁鸡的小窝拿到今日头条的offer！加油！</p>
 <img src="{% static 'images/chick.jpg' %}"
            alt="Picture of NaiPP" />
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %} <!--tell templates the staticfile will be used -->


{% block body_block %}
        <h2>现在可以给何屁鸡的小窝添加东西啦@#@</h2>
        <div>
            <form id="category_form" method="post" action="/rango/add_category/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{hidden}}
                {% endfor %}
                {% for field in form.visible_fields %}
                <p>{{ field.errors }}</p>
                <p>{{ field.help_text }}</p>
                <p>{{ field }}</p>
                {% endfor %}
                <input type="submit" name="submit" value="Create Category" />
            </form>
        </div><br />
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %} <!--tell templates the staticfile will be used -->


{% block body_block %}
        <h2>又要给何屁鸡的小窝添加东西了嘛@@ 你真好@~@</h2>
        <div>
            <form id="Page_form" method="post" action="/rango/category/{{category.slug}}/add_page/" enctype="multipart/form-data">
                {% csrf_token %}
                {% if category %}
                {% for hidden in form.hidden_fields %}
                    {{hidden}}
                {% endfor %}
                {% for field in form.visible_fields %}
                <p> {{ field.errors }}</p>
                <p> {{ field.help_text }}</p>
                <p>{{ field }}</p>
                {% endfor %}
                {% else %}
            <strong>A category by this name does not exist.</strong>
                {% endif %}
                <input type="submit" name="submit" value="Create Page" />
            </form>
        </div><br />
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'js/rango-jquery.js' %}"></script>
<script src="{% static 'js/rango-ajax.js' %}"></script>


<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>
        {% block title %}何屁鸡的小窝{% endblock %}
    </title>


    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
          rel="stylesheet">
</head>

<style type="text/css">
.main{margin-top:35px;}
</style>
<body>

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'rango:index' %}">PIJI</a>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'rango:index' %}">
                    Home
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:about' %}">
                    About
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:profile' user.username %}">
                    Profile
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:add_category' %}">
                    Add a New Category
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">
                    Register Here
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">
                    Login
                </a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:search' %}">
                    Search
                </a>
            </li>
        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% block sidebar_block %}
            {% get_category_list category %}
            {% endblock %}
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
            {% block body_block %}{% endblock %}
        </div>
    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>

<script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script
        src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
</script>
</body>
</html>

tango_with_django_project/templates/rango/base_boot-strap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>
        {% block title %}何屁鸡的小窝{% endblock %}
    </title>


    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
          rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'rango:index' %}">PIJI</a>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'rango:index' %}">
                    Home
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:about' %}">
                    About
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'restricted' %}">
                    屁鸡er only
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:add_category' %}">
                    Add a New Category
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">
                    Register Here
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">
                    Login
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% block sidebar_block %}
            {% get_category_list category %}
            {% endblock %}
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
            {% block body_block %}{% endblock %}
        </div>
    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script
        src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
</script>
</body>
</html>

tango_with_django_project/templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>
        {% block title %}何屁鸡的小窝{% endblock %}
    </title>


    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
          rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'rango:index' %}">PIJI</a>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'rango:index' %}">
                    Home
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:about' %}">
                    About
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'restricted' %}">
                    屁鸡er only
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:add_category' %}">
                    Add a New Category
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">
                    Register Here
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">
                    Login
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% block sidebar_block %}
            {% get_category_list category %}
            {% endblock %}
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
            {% block body_block %}{% endblock %}
        </div>
    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script
        src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
</script>
</body>
</html>

tango_with_django_project/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
            <li>
                <strong>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </strong>
            </li>
            {% else %}
            <li>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
    {% endif %}
    {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}

</ul>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %} <!--tell templates the staticfile will be used -->



    {% block body_block %}
    <div class="jumbotron">
        <h1 class="display-3">何屁鸡说：
            </h1>
    {% if user.is_authenticated %}
       <h3>Hi~ 屁鸡er_{{ user.username }}! This is your {{visits}} time(s) visit us!!</h3>
    {% else %}
        <h3>Hey there 屁鸡er! This is your {{visits}} time(s) visit us!!</h3>
    {% endif %}
    </div>


    <div class="row marketing">
        <div class="col-lg-6">
        <h4> Most Liked Categories </h4>
        <p>
        {% if categories %}
        <ul class="list-group">
            {% for category in categories %}
                <li class="list-group-item">
                    <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        </p>
        </div>

    <div class="col-lg-6">
    <h4> Most Viewed Pages </h4>
    <p>
        {% if pages %}
        <ul class="list-group">
            {% for page in pages %}
            <li class="list-group-item">
                <a href="{% url 'rango:show_page' page.slug %}">{{page.title}}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong> There are no pages present </strong>
        {% endif %}
    </p>
    </div>
    </div>


{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}

<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
{% csrf_token %}
Username: <input type="text" name="username" value="" size="50" />
<br />
Password: <input type="password" name="password" value="" size="50" />
<br />
<input type="submit" value="submit" />
</form>

{% endblock %}

tango_with_django_project/templates/rango/page.html
{% extends 'rango/base.html' %}
{% load staticfiles %} <!--tell templates the staticfile will be used -->



    {% block body_block %}
        {% if pages %}
        <h2>{{ pages.title }} </h2>
        <p>Description: {{pages.txt}}</p>
        <p>Views: {{pages.views}}</p>
        <p>File: {{pages.file}}</p>
        <p><a href="{{pages.url}}">🔗原文链接🔗</a></p>
        {% if pages.file %}
        <p><a href="http://106.14.174.96:8000/media/{{pages.file}}" type="button">Download File</a></p>
        {% endif %}
        {% else %}
        <strong>No pages currently in category.</strong>
        {% endif %}

    {% endblock %}

tango_with_django_project/templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for 何屁鸡的小窝</h1>
    {% if registered %}
        屁鸡 says: <strong>谢谢你对小窝的关注@~@</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage</a><br />
    {% else %}
        屁鸡 says: <strong>{{user}} hi!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}"
              enctype="multipart/form-data">
            {% csrf_token %}

            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load bootstrap_toolkit %}


{% block title %}Search{% endblock %}

{% block body_block %}
<div>
    <h1>小屁鸡帮你找~</h1>
    <br />
    <form class="form-inline" id="user_form"
          method="post" action="{% url 'rango:search' %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50"
                   name="query" value="{{query}}" id="query" />
        </div>
        <button class="btn btn-primary" type="submit" name="submit"
                value="Search">Search</button>
    </form>
    <div>
        {% if result_list %}
        <h3>Results</h3>
        <div class="list-group">
            {% for result in result_list %}
            <div class="list-group-item">
                <h4 class="list-group-item-heading">
                    <a href="{{ result.link }}">{{ result.title }}</a>
                </h4>
                <p class="list-group-item-text">{{ result.summary }}</p>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}